import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export const RECIPES_DATA = [
  {
    id: "recipe-001",
    name: "Cơm tấm sườn bì chả",
    image: "🍚",
    calories: 650,
    cookTime: 35,
    servings: 2,
    cost: 35000,
    category: "com",
    tags: ["protein cao", "no lâu"],
    ingredients: [
      { name: "Sườn heo", amount: "300g", estimatedPrice: 25000 },
      { name: "Gạo tấm", amount: "200g", estimatedPrice: 5000 },
      { name: "Bì heo", amount: "100g", estimatedPrice: 8000 },
      { name: "Trứng", amount: "2 quả", estimatedPrice: 6000 },
      { name: "Đồ chua", amount: "1 chén", estimatedPrice: 3000 },
      { name: "Nước mắm pha", amount: "50ml", estimatedPrice: 2000 },
    ],
    steps: [
      "Ướp sườn với sả, tỏi, nước mắm, đường 30 phút",
      "Nấu cơm tấm bằng gạo tấm",
      "Nướng / chiên sườn đến vàng đều",
      "Chiên trứng ốp la, trộn bì",
      "Bày cơm ra đĩa, xếp sườn, bì, chả, trứng lên trên",
    ],
    rating: 4.8,
    reviews: 124,
  },
  {
    id: "recipe-002",
    name: "Bún bò Huế",
    image: "🍜",
    calories: 520,
    cookTime: 60,
    servings: 4,
    cost: 30000,
    category: "bun-pho",
    tags: ["đậm đà", "truyền thống"],
    ingredients: [
      { name: "Bắp bò", amount: "500g", estimatedPrice: 40000 },
      { name: "Giò heo", amount: "300g", estimatedPrice: 20000 },
      { name: "Bún tươi", amount: "500g", estimatedPrice: 10000 },
      { name: "Sả", amount: "5 cây", estimatedPrice: 3000 },
      { name: "Mắm ruốc", amount: "2 muỗng", estimatedPrice: 5000 },
      { name: "Rau sống", amount: "1 bó", estimatedPrice: 5000 },
    ],
    steps: [
      "Ninh xương bò, giò heo 2 tiếng lấy nước dùng",
      "Phi sả băm, thêm mắm ruốc tạo màu",
      "Nêm nếm vừa ăn, thêm ớt sa tế",
      "Trụng bún, xếp thịt bò, giò heo lên trên",
      "Chan nước dùng nóng, ăn kèm rau sống",
    ],
    rating: 4.9,
    reviews: 256,
  },
  {
    id: "recipe-003",
    name: "Cơm rang dưa bò",
    image: "🍳",
    calories: 480,
    cookTime: 15,
    servings: 1,
    cost: 25000,
    category: "com",
    tags: ["nhanh", "tiết kiệm"],
    ingredients: [
      { name: "Cơm nguội", amount: "1 bát to", estimatedPrice: 3000 },
      { name: "Thịt bò", amount: "100g", estimatedPrice: 15000 },
      { name: "Dưa chua", amount: "50g", estimatedPrice: 3000 },
      { name: "Hành lá", amount: "2 cây", estimatedPrice: 1000 },
      { name: "Trứng", amount: "1 quả", estimatedPrice: 3000 },
      { name: "Gia vị", amount: "ít", estimatedPrice: 2000 },
    ],
    steps: [
      "Xào thịt bò tái với tỏi, dầu hào",
      "Cho dưa chua vào xào nhanh",
      "Thêm cơm nguội, đảo đều lửa lớn",
      "Nêm nước mắm, tiêu vừa ăn",
      "Rắc hành lá, ăn kèm trứng ốp la",
    ],
    rating: 4.6,
    reviews: 89,
  },
  {
    id: "recipe-004",
    name: "Phở bò tái nạm",
    image: "🍲",
    calories: 450,
    cookTime: 90,
    servings: 4,
    cost: 28000,
    category: "bun-pho",
    tags: ["truyền thống", "ấm bụng"],
    ingredients: [
      { name: "Xương bò", amount: "1kg", estimatedPrice: 35000 },
      { name: "Thịt bò tái", amount: "200g", estimatedPrice: 25000 },
      { name: "Nạm bò", amount: "200g", estimatedPrice: 20000 },
      { name: "Bánh phở", amount: "400g", estimatedPrice: 10000 },
      { name: "Hành tây", amount: "1 củ", estimatedPrice: 3000 },
      { name: "Gừng, quế, hồi", amount: "ít", estimatedPrice: 5000 },
    ],
    steps: [
      "Ninh xương bò 3-4 tiếng, vớt bọt",
      "Nướng hành tây, gừng rồi cho vào nồi",
      "Thêm quế, hồi, nêm nước mắm",
      "Trụng bánh phở, xếp thịt tái, nạm",
      "Chan nước dùng sôi, ăn kèm giá, rau thơm",
    ],
    rating: 4.9,
    reviews: 312,
  },
  {
    id: "recipe-005",
    name: "Canh chua cá lóc",
    image: "🐟",
    calories: 280,
    cookTime: 25,
    servings: 3,
    cost: 32000,
    category: "canh",
    tags: ["nhẹ bụng", "vitamin"],
    ingredients: [
      { name: "Cá lóc", amount: "400g", estimatedPrice: 25000 },
      { name: "Thơm (dứa)", amount: "1/2 trái", estimatedPrice: 5000 },
      { name: "Cà chua", amount: "2 trái", estimatedPrice: 4000 },
      { name: "Đậu bắp", amount: "100g", estimatedPrice: 3000 },
      { name: "Me", amount: "30g", estimatedPrice: 3000 },
      { name: "Rau ngò om", amount: "1 bó", estimatedPrice: 2000 },
    ],
    steps: [
      "Nấu nước dùng với me, thơm, cà chua",
      "Cho cá lóc vào nấu chín",
      "Thêm đậu bắp, giá đỗ",
      "Nêm nước mắm, đường vừa ăn",
      "Rắc ngò om, ăn kèm cơm trắng",
    ],
    rating: 4.7,
    reviews: 78,
  },
  {
    id: "recipe-006",
    name: "Bánh mì ốp la",
    image: "🥖",
    calories: 380,
    cookTime: 10,
    servings: 1,
    cost: 15000,
    category: "an-sang",
    tags: ["nhanh", "rẻ", "tiện"],
    ingredients: [
      { name: "Bánh mì", amount: "1 ổ", estimatedPrice: 3000 },
      { name: "Trứng", amount: "2 quả", estimatedPrice: 6000 },
      { name: "Pate", amount: "1 muỗng", estimatedPrice: 3000 },
      { name: "Rau, dưa leo", amount: "ít", estimatedPrice: 2000 },
      { name: "Nước tương, ớt", amount: "ít", estimatedPrice: 1000 },
    ],
    steps: [
      "Chiên trứng ốp la 2 quả",
      "Nướng giòn bánh mì",
      "Phết pate vào ruột bánh",
      "Kẹp trứng, rau, dưa leo",
      "Rưới nước tương, ớt tùy khẩu vị",
    ],
    rating: 4.5,
    reviews: 203,
  },
  {
    id: "recipe-007",
    name: "Gỏi cuốn tôm thịt",
    image: "🥬",
    calories: 220,
    cookTime: 20,
    servings: 2,
    cost: 22000,
    category: "chay",
    tags: ["healthy", "ít calo"],
    ingredients: [
      { name: "Bánh tráng", amount: "10 cái", estimatedPrice: 5000 },
      { name: "Tôm", amount: "200g", estimatedPrice: 15000 },
      { name: "Thịt ba chỉ luộc", amount: "100g", estimatedPrice: 10000 },
      { name: "Bún tươi", amount: "100g", estimatedPrice: 3000 },
      { name: "Rau sống các loại", amount: "1 bó", estimatedPrice: 5000 },
      { name: "Tương đậu phộng", amount: "50ml", estimatedPrice: 4000 },
    ],
    steps: [
      "Luộc tôm, thịt ba chỉ, để nguội thái lát",
      "Chuẩn bị rau sống, bún",
      "Nhúng bánh tráng nước ấm, trải ra",
      "Xếp rau, bún, thịt, tôm rồi cuốn chặt",
      "Chấm tương đậu phộng",
    ],
    rating: 4.7,
    reviews: 91,
  },
  {
    id: "recipe-008",
    name: "Xôi xéo",
    image: "🫘",
    calories: 420,
    cookTime: 40,
    servings: 2,
    cost: 18000,
    category: "an-sang",
    tags: ["truyền thống", "no lâu"],
    ingredients: [
      { name: "Gạo nếp", amount: "300g", estimatedPrice: 8000 },
      { name: "Đậu xanh", amount: "100g", estimatedPrice: 5000 },
      { name: "Hành phi", amount: "50g", estimatedPrice: 5000 },
      { name: "Mỡ hành", amount: "2 muỗng", estimatedPrice: 3000 },
      { name: "Nghệ", amount: "ít", estimatedPrice: 2000 },
    ],
    steps: [
      "Ngâm nếp 4 tiếng, trộn nghệ, hấp chín",
      "Nấu nhuyễn đậu xanh, tán mịn",
      "Phi hành khô giòn vàng",
      "Xới xôi ra, phủ đậu xanh, rưới mỡ hành",
      "Rắc hành phi lên trên",
    ],
    rating: 4.6,
    reviews: 67,
  },
];

export const COMMUNITY_POSTS_DATA = [
  {
    id: "post-001",
    authorName: "Minh Tuấn",
    authorAvatar: "👨‍🍳",
    authorBadge: "Top Contributor",
    authorRole: "Đam mê nấu ăn · 4 năm tự nấu",
    title: "Kế hoạch ăn 1 tuần chỉ 350K đủ chất cho 1 người",
    content: "Mình chia sẻ thực đơn 7 ngày đầy đủ dinh dưỡng, chi phí bình quân 50K/ngày. Bí quyết là mua nguyên liệu theo mùa, chia nhỏ khẩu phần và nấu trước cho 2-3 ngày...",
    category: "meal-plan",
    likes: 234,
    comments: 45,
    views: 1289,
    tags: ["50K/ngày", "meal-prep", "tiết kiệm"],
    mealPlan: { days: 7, avgCost: 50000 },
  },
  {
    id: "post-002",
    authorName: "Cô Thanh Mai",
    authorAvatar: "👵",
    authorBadge: "Nội Trợ Thông Thái",
    authorRole: "20 năm kinh nghiệm nội trợ",
    title: "5 loại trái cây mùa thu vừa ngon vừa rẻ ở chợ",
    content: "Vào mùa thu, bưởi da xanh, cam sành, hồng giòn và ổi đang rộ với giá cực kỳ tốt. Mẹo của cô là đi chợ vào tầm 6h - 7h sáng, vừa tươi ngon mà giá mềm hơn siêu thị đáng kể...",
    category: "seasonal",
    likes: 167,
    comments: 28,
    views: 876,
    tags: ["trái cây", "theo mùa", "mẹo nội trợ"],
  },
  {
    id: "post-003",
    authorName: "Anh Đức Anh",
    authorAvatar: "👨‍💻",
    authorBadge: "Dân Văn Phòng",
    authorRole: "Nhân viên IT · Meal-prep cuối tuần",
    title: "Cách chọn thịt, cá tươi ngon khi đi siêu thị & chợ truyền thống",
    content: "Nhiều người bận rộn ít đi chợ thường lúng túng khi chọn thực phẩm. Chia sẻ vài mẹo đơn giản: thịt heo tươi có màu hồng nhạt, thớ thịt săn chắc, ấn tay đàn hồi ngay, bề mặt khô ráo không nhờn rít...",
    category: "tips",
    likes: 198,
    comments: 32,
    views: 1034,
    tags: ["chọn thực phẩm", "đi chợ", "kinh nghiệm"],
  },
  {
    id: "post-004",
    authorName: "Thu Hương",
    authorAvatar: "👩‍🍳",
    authorBadge: "Eat-clean Master",
    authorRole: "HLV Dinh dưỡng cá nhân",
    title: "Thực đơn eat-clean 30 ngày lành mạnh, dưới 60K/người/ngày",
    content: "Ăn healthy không hề đắt đỏ nếu biết phối hợp nguyên liệu địa phương. Mình tận dụng ức gà, trứng, đậu hũ và rau củ theo mùa. Vừa giữ dáng, tốt cho sức khỏe mà không lo 'viêm màng túi'...",
    category: "meal-plan",
    likes: 312,
    comments: 67,
    views: 2341,
    tags: ["eat-clean", "healthy", "dinh dưỡng"],
    mealPlan: { days: 30, avgCost: 55000 },
  },
  {
    id: "post-005",
    authorName: "Bác Quốc Bảo",
    authorAvatar: "👨‍🌾",
    authorRole: "Tiểu thương chợ đầu mối",
    title: "Những điều cần biết khi đi chợ đầu mối mua đồ ăn cho cả tuần",
    content: "Đi chợ đầu mối hoặc gom mua theo nhóm gia đình, bạn bè giúp tiết kiệm 30-40%. Nên chuẩn bị hộp bảo quản sạch, phân chia thịt cá cấp đông theo từng bữa để không bị mất chất...",
    category: "tips",
    likes: 145,
    comments: 52,
    views: 789,
    tags: ["chợ đầu mối", "bảo quản", "tiết kiệm"],
  },
  {
    id: "post-006",
    authorName: "Chị Lan Phương",
    authorAvatar: "👩‍👧‍👦",
    authorBadge: "Mẹ Thông Thái",
    authorRole: "Mẹ bỉm 2 con · Quản lý chi tiêu gia đình",
    title: "Bảng mùa vụ nông sản 2026 – Mua rau củ quả tháng nào rẻ và an toàn nhất",
    content: "Rau củ đúng mùa vụ thường ít tồn dư thuốc bảo vệ thực vật và giá mềm nhất. Từ tháng 10 trở đi là mùa bắp cải, su hào, súp lơ giá chỉ bằng 1/2 so với trái vụ...",
    category: "seasonal",
    likes: 267,
    comments: 41,
    views: 1567,
    tags: ["nông sản", "mùa vụ", "gia đình"],
  },
];

export const SAMPLE_MEAL_PLANS = [
  {
    date: "2026-10-05",
    slot: "breakfast",
    meal: "Xôi xéo",
    calories: 420,
    cost: 15000,
    ingredients: ["Nếp", "Đậu xanh", "Hành phi"],
  },
  {
    date: "2026-10-05",
    slot: "lunch",
    meal: "Cơm rang dưa bò",
    calories: 480,
    cost: 25000,
    ingredients: ["Cơm nguội", "Thịt bò", "Dưa chua"],
  },
  {
    date: "2026-10-05",
    slot: "dinner",
    meal: "Canh chua cá lóc",
    calories: 280,
    cost: 20000,
    ingredients: ["Cá lóc", "Thơm", "Cà chua"],
  },
  {
    date: "2026-10-05",
    slot: "snack",
    meal: "Chuối + sữa chua",
    calories: 150,
    cost: 10000,
    ingredients: ["Chuối", "Sữa chua"],
  },
  {
    date: "2026-10-06",
    slot: "breakfast",
    meal: "Bánh mì ốp la",
    calories: 380,
    cost: 15000,
    ingredients: ["Bánh mì", "Trứng", "Pate"],
  },
  {
    date: "2026-10-06",
    slot: "lunch",
    meal: "Bún bò Huế",
    calories: 520,
    cost: 30000,
    ingredients: ["Bún", "Bò", "Sả", "Mắm ruốc"],
  },
  {
    date: "2026-10-06",
    slot: "dinner",
    meal: "Gỏi cuốn tôm thịt",
    calories: 220,
    cost: 22000,
    ingredients: ["Bánh tráng", "Tôm", "Thịt"],
  },
  {
    date: "2026-10-07",
    slot: "breakfast",
    meal: "Phở bò tái nạm",
    calories: 450,
    cost: 28000,
    ingredients: ["Bánh phở", "Bò", "Hành"],
  },
  {
    date: "2026-10-07",
    slot: "lunch",
    meal: "Cơm tấm sườn bì chả",
    calories: 650,
    cost: 35000,
    ingredients: ["Gạo tấm", "Sườn", "Đồ chua"],
  },
  {
    date: "2026-10-07",
    slot: "dinner",
    meal: "Rau xào thập cẩm",
    calories: 200,
    cost: 15000,
    ingredients: ["Cải ngọt", "Nấm", "Cà rốt"],
  },
];

async function seedMealPlanner() {
  console.log('[MealPlanner] Seeding Recipes...');
  for (const r of RECIPES_DATA) {
    await prisma.recipe.upsert({
      where: { id: r.id },
      update: r,
      create: r,
    });
  }

  console.log('[MealPlanner] Seeding Community Posts...');
  for (const p of COMMUNITY_POSTS_DATA) {
    await prisma.communityPost.upsert({
      where: { id: p.id },
      update: p,
      create: p,
    });
  }

  console.log('[MealPlanner] Seeding Meal Plans...');
  for (const mp of SAMPLE_MEAL_PLANS) {
    const existing = await prisma.mealPlan.findFirst({
      where: { date: mp.date, slot: mp.slot, userId: null },
    });
    if (!existing) {
      await prisma.mealPlan.create({ data: mp });
    }
  }

  console.log('✅ [MealPlanner] Successfully seeded recipes, community posts, and meal plans!');
}

seedMealPlanner()
  .catch((err) => {
    console.error('Error seeding meal planner:', err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
