import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export const RECIPES_DATA = [
  {
    id: "recipe-001",
    name: "Cơm tấm sườn bì chả",
    image: "/images/img-foodsaver/C%C6%A1m%20s%C6%B0%E1%BB%9Dn%20n%C6%B0%E1%BB%9Bng%20tr%E1%BB%A9ng%20%E1%BB%91p%20la.png",
    calories: 650,
    cookTime: 35,
    servings: 2,
    cost: 35000,
    category: "com",
    tags: ["protein cao", "no lâu", "đặc sản Sài Gòn"],
    ingredients: [
      { name: "Sườn heo", amount: "300g", estimatedPrice: 25000 },
      { name: "Gạo tấm", amount: "200g", estimatedPrice: 5000 },
      { name: "Bì heo", amount: "100g", estimatedPrice: 8000 },
      { name: "Trứng", amount: "2 quả", estimatedPrice: 6000 },
      { name: "Đồ chua & mỡ hành", amount: "1 chén", estimatedPrice: 3000 },
      { name: "Nước mắm pha tỏi ớt", amount: "50ml", estimatedPrice: 2000 },
    ],
    steps: [
      "Ướp sườn cốt lết với sả, hành tím, dầu hào, mật ong 30 phút",
      "Nấu cơm tấm bằng nồi cơm điện hoặc xửng hấp",
      "Nướng sườn trên than hoa hoặc nồi chiên không dầu ở 180°C đến khi vàng thơm",
      "Chiên trứng ốp la lòng đào, trộn bì heo với thính gạo",
      "Bày cơm ra đĩa, xếp sườn nướng, bì chả, trứng, rưới mỡ hành và chan nước mắm chua ngọt",
    ],
    rating: 4.9,
    reviews: 184,
  },
  {
    id: "recipe-002",
    name: "Bún bò Huế",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800",
    calories: 520,
    cookTime: 60,
    servings: 4,
    cost: 30000,
    category: "bun-pho",
    tags: ["đậm đà", "truyền thống", "ấm bụng"],
    ingredients: [
      { name: "Bắp bò hoa", amount: "400g", estimatedPrice: 40000 },
      { name: "Giò heo / chả cua", amount: "300g", estimatedPrice: 20000 },
      { name: "Bún sợi to", amount: "500g", estimatedPrice: 10000 },
      { name: "Sả cây & ớt sa tế", amount: "5 cây", estimatedPrice: 3000 },
      { name: "Mắm ruốc Huế", amount: "2 muỗng", estimatedPrice: 5000 },
      { name: "Rau muống chẻ, hoa chuối", amount: "1 rổ", estimatedPrice: 6000 },
    ],
    steps: [
      "Hầm xương ống bò và bắp bò với sả đập dập trong 1.5 giờ",
      "Khuấy mắm ruốc với nước lạnh, gạn lấy nước trong cho vào nồi",
      "Phi thơm sả ớt tạo màu sa tế đỏ au bắt mắt",
      "Trụng bún nước sôi, thái bắp bò mỏng và xếp chả cua lên trên",
      "Chan nước dùng sôi sùng sục, vắt chanh và ăn kèm rau sống tươi giòn",
    ],
    rating: 4.9,
    reviews: 295,
  },
  {
    id: "recipe-003",
    name: "Cơm rang dưa bò",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800",
    calories: 480,
    cookTime: 15,
    servings: 1,
    cost: 25000,
    category: "com",
    tags: ["nhanh gọn", "tiết kiệm", "bữa trưa"],
    ingredients: [
      { name: "Cơm nguội", amount: "1 tô to", estimatedPrice: 3000 },
      { name: "Thịt bò thăn", amount: "100g", estimatedPrice: 16000 },
      { name: "Dưa cải muối chua", amount: "60g", estimatedPrice: 3000 },
      { name: "Trứng gà", amount: "1 quả", estimatedPrice: 3000 },
      { name: "Hành khô & hành lá", amount: "ít", estimatedPrice: 2000 },
    ],
    steps: [
      "Bóp đều cơm nguội với 1 lòng đỏ trứng để hạt cơm tơi xốp và vàng óng",
      "Phi thơm tỏi, xào nhanh thịt bò với dầu hào lửa lớn rồi xúc ra đĩa",
      "Xào dưa chua cho săn giòn",
      "Cho cơm vào chảo đảo liên tục đến khi săn hạt",
      "Trút thịt bò và dưa vào đảo đều 1 phút, rắc hành lá tiêu đen",
    ],
    rating: 4.7,
    reviews: 142,
  },
  {
    id: "recipe-004",
    name: "Phở bò tái nạm",
    image: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800",
    calories: 450,
    cookTime: 90,
    servings: 4,
    cost: 28000,
    category: "bun-pho",
    tags: ["truyền thống", "tinh hoa", "bữa sáng"],
    ingredients: [
      { name: "Xương ống bò", amount: "800g", estimatedPrice: 30000 },
      { name: "Thịt thăn bò tươi", amount: "200g", estimatedPrice: 25000 },
      { name: "Nạm bò luộc", amount: "200g", estimatedPrice: 20000 },
      { name: "Bánh phở tươi", amount: "500g", estimatedPrice: 12000 },
      { name: "Gừng, hồi, quế, thảo quả", amount: "1 gói", estimatedPrice: 5000 },
      { name: "Hành tây, hành hoa, ngò gai", amount: "1 bó", estimatedPrice: 4000 },
    ],
    steps: [
      "Nướng thơm hành tây, gừng, hồi, quế rồi thả vào nồi ninh xương bò",
      "Ninh lửa liu riu 2-3 tiếng, vớt bọt liên tục để nước dùng trong veo",
      "Nêm nước mắm cốt nhĩ loại ngon và chút đường phèn thanh ngọt",
      "Trần bánh phở, xếp nạm bò thái mỏng và thịt bò tái",
      "Chan nước phở thật sôi, rắc hành chẻ và thưởng thức nóng hổi",
    ],
    rating: 5.0,
    reviews: 420,
  },
  {
    id: "recipe-005",
    name: "Canh chua cá lóc",
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=800",
    calories: 280,
    cookTime: 25,
    servings: 3,
    cost: 32000,
    category: "canh",
    tags: ["thanh mát", "giải nhiệt", "dân dã"],
    ingredients: [
      { name: "Cá lóc đồng", amount: "400g", estimatedPrice: 26000 },
      { name: "Dứa (thơm)", amount: "1/2 trái", estimatedPrice: 5000 },
      { name: "Cà chua & đậu bắp", amount: "200g", estimatedPrice: 5000 },
      { name: "Me chua dầm", amount: "40g", estimatedPrice: 3000 },
      { name: "Bạc hà (dọc mùng) & giá", amount: "150g", estimatedPrice: 4000 },
      { name: "Ngò gai & ngò om", amount: "1 nhúm", estimatedPrice: 2000 },
    ],
    steps: [
      "Cá lóc làm sạch, cắt khúc ướp với chút hạt nêm, tiêu, hành tím",
      "Nấu nước sôi, dầm me chua lấy nước cốt đổ vào nồi",
      "Thả cá vào nấu chín tới, vớt bọt kỹ",
      "Cho dứa, cà chua, bạc hà, đậu bắp vào đun sôi thêm 2 phút",
      "Tắt bếp, cho giá đỗ và ngò om ngò gai, nêm mắm ngon vừa miệng",
    ],
    rating: 4.8,
    reviews: 110,
  },
  {
    id: "recipe-006",
    name: "Bánh mì ốp la pate",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?w=800",
    calories: 380,
    cookTime: 10,
    servings: 1,
    cost: 15000,
    category: "an-sang",
    tags: ["nhanh gọn", "siêu rẻ", "tiện lợi"],
    ingredients: [
      { name: "Bánh mì giòn rụm", amount: "1 ổ", estimatedPrice: 3000 },
      { name: "Trứng gà tươi", amount: "2 quả", estimatedPrice: 6000 },
      { name: "Pate gan thơm bùi", amount: "30g", estimatedPrice: 4000 },
      { name: "Dưa chuột & đồ chua", amount: "50g", estimatedPrice: 2000 },
      { name: "Nước tương & ớt tươi", amount: "ít", estimatedPrice: 1000 },
    ],
    steps: [
      "Chiên 2 quả trứng ốp la lòng đào trên chảo bơ nóng",
      "Nướng lại bánh mì cho giòn rụm vỏ ngoài",
      "Phết đều lớp pate gan bùi ngậy vào thành trong ruột bánh",
      "Kẹp trứng ốp la, dưa chuột thái lát và đồ chua cà rốt",
      "Rưới chút nước tương ớt cay nồng, cắn miếng giòn rụm khó cưỡng",
    ],
    rating: 4.7,
    reviews: 312,
  },
  {
    id: "recipe-007",
    name: "Gỏi cuốn tôm thịt",
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800",
    calories: 220,
    cookTime: 20,
    servings: 2,
    cost: 22000,
    category: "chay",
    tags: ["healthy", "eat-clean", "ít calo"],
    ingredients: [
      { name: "Tôm sú tươi", amount: "200g", estimatedPrice: 16000 },
      { name: "Thịt ba chỉ luộc", amount: "120g", estimatedPrice: 12000 },
      { name: "Bánh tráng dẻo", amount: "1 xấp", estimatedPrice: 4000 },
      { name: "Bún tươi", amount: "150g", estimatedPrice: 3000 },
      { name: "Rau xà lách, hẹ, rau thơm", amount: "1 rổ", estimatedPrice: 5000 },
      { name: "Tương đen chấm đậu phộng", amount: "1 chén", estimatedPrice: 4000 },
    ],
    steps: [
      "Luộc chín tôm lột vỏ chẻ đôi, luộc thịt ba chỉ thái lát mỏng",
      "Làm ướt nhẹ bánh tráng dẻo trên mặt phẳng sạch",
      "Xếp rau xà lách, bún, thịt luộc rồi cuộn một vòng",
      "Đặt hàng tôm đỏ và cọng hẹ thò ra ngoài rồi cuộn chặt tay",
      "Chấm cùng sốt tương đậu phộng béo ngậy rắc hành phi thơm",
    ],
    rating: 4.8,
    reviews: 178,
  },
  {
    id: "recipe-008",
    name: "Xôi xéo mỡ hành ruốc",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800",
    calories: 420,
    cookTime: 40,
    servings: 2,
    cost: 18000,
    category: "an-sang",
    tags: ["no lâu", "truyền thống", "bữa sáng"],
    ingredients: [
      { name: "Gạo nếp cái hoa vàng", amount: "300g", estimatedPrice: 9000 },
      { name: "Đậu xanh cà vỏ", amount: "120g", estimatedPrice: 6000 },
      { name: "Hành phi vàng giòn", amount: "50g", estimatedPrice: 5000 },
      { name: "Mỡ gà phi hành", amount: "2 muỗng", estimatedPrice: 3000 },
      { name: "Chà bông / ruốc thịt", amount: "30g", estimatedPrice: 5000 },
    ],
    steps: [
      "Ngâm nếp cùng chút bột nghệ, đồ xôi chín mềm dẻo hạt",
      "Hấp chín đậu xanh, giã nhuyễn rồi nắm thành từng quả tròn chặt tay",
      "Phi hành ta với mỡ gà thơm nức mũi",
      "Xới xôi vàng óng ra lá chuối, dùng dao mỏng gọt lát đậu xanh phủ đều",
      "Rưới mỡ gà óng ả, rắc đẫm hành phi giòn tan và chút chà bông",
    ],
    rating: 4.8,
    reviews: 95,
  },
  {
    id: "recipe-009",
    name: "Thịt kho tàu trứng cút",
    image: "/images/img-foodsaver/B%E1%BB%AFa%20c%C6%A1m%20Vi%E1%BB%87t%20n%C3%B3ng%20h%E1%BB%95i%20d%C3%A2n%20d%C3%A3.png",
    calories: 550,
    cookTime: 45,
    servings: 3,
    cost: 32000,
    category: "com",
    tags: ["đậm vị", "bữa tối gia đình", "chuẩn vị"],
    ingredients: [
      { name: "Thịt ba chỉ rút sườn", amount: "350g", estimatedPrice: 28000 },
      { name: "Trứng cút luộc bóc vỏ", amount: "10 quả", estimatedPrice: 8000 },
      { name: "Nước dừa tươi", amount: "1 trái", estimatedPrice: 10000 },
      { name: "Nước mắm & đường thắng caramel", amount: "vừa đủ", estimatedPrice: 3000 },
      { name: "Hành tím, tỏi, ớt", amount: "ít", estimatedPrice: 2000 },
    ],
    steps: [
      "Thái thịt miếng vuông to bản, ướp hành tím, tỏi băm, tiêu, mắm ngon 20 phút",
      "Thắng đường vàng cánh gián, cho thịt vào đảo săn màu caramel",
      "Đổ nước dừa xiêm ngập thịt, đun sôi rồi hạ lửa liu riu",
      "Thêm trứng cút vào kho cùng đến khi nước sốt sánh sệt nâu óng",
      "Ăn kèm cơm trắng nóng hổi và dưa cải muối chua",
    ],
    rating: 4.9,
    reviews: 215,
  },
  {
    id: "recipe-010",
    name: "Bò kho bánh mì",
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=800",
    calories: 580,
    cookTime: 50,
    servings: 3,
    cost: 35000,
    category: "bun-pho",
    tags: ["đậm đà", "ấm áp", "dễ ăn"],
    ingredients: [
      { name: "Nạm & gân bò", amount: "350g", estimatedPrice: 38000 },
      { name: "Cà rốt & củ cải", amount: "2 củ", estimatedPrice: 6000 },
      { name: "Gói sốt gia vị bò kho", amount: "1 gói", estimatedPrice: 6000 },
      { name: "Sả đập dập & nước dừa", amount: "vừa đủ", estimatedPrice: 8000 },
      { name: "Bánh mì nóng giòn", amount: "3 ổ", estimatedPrice: 9000 },
    ],
    steps: [
      "Ướp thịt bò với gia vị bò kho, sả, hành tỏi 30 phút",
      "Xào săn bò lửa lớn rồi đổ nước dừa ninh mềm trong 40 phút",
      "Cho cà rốt cắt khúc vào hầm thêm 10 phút",
      "Pha chút bột năng tạo độ sánh óng ánh cho nước xốt",
      "Múc ra tô rắc ngò gai, chấm cùng bánh mì nướng giòn",
    ],
    rating: 4.8,
    reviews: 130,
  },
  {
    id: "recipe-011",
    name: "Salad ức gà sốt mè rang",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800",
    calories: 320,
    cookTime: 15,
    servings: 1,
    cost: 24000,
    category: "salad",
    tags: ["eat-clean", "giảm cân", "protein cao"],
    ingredients: [
      { name: "Ức gà phi lê áp chảo", amount: "150g", estimatedPrice: 15000 },
      { name: "Xà lách romaine & cải mầm", amount: "100g", estimatedPrice: 6000 },
      { name: "Cà chua bi & dưa leo", amount: "80g", estimatedPrice: 4000 },
      { name: "Trứng luộc", amount: "1 quả", estimatedPrice: 3000 },
      { name: "Sốt mè rang Kewpie", amount: "30ml", estimatedPrice: 4000 },
    ],
    steps: [
      "Ức gà ướp chút muối tiêu, áp chảo vàng 2 mặt rồi xé sợi",
      "Rửa sạch rau xà lách để ráo, cắt cà chua bi đôi",
      "Bày rau, dưa leo, cà chua, trứng luộc cắt lát ra đĩa sâu lòng",
      "Xếp ức gà lên trên và rưới đều xốt mè rang béo thơm",
      "Trộn đều và thưởng thức bữa trưa lành mạnh tràn đầy năng lượng",
    ],
    rating: 4.9,
    reviews: 87,
  },
  {
    id: "recipe-012",
    name: "Cháo sườn sụn quẩy giòn",
    image: "https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=800",
    calories: 390,
    cookTime: 40,
    servings: 2,
    cost: 20000,
    category: "an-sang",
    tags: ["ấm bụng", "dễ tiêu hóa", "bữa sáng"],
    ingredients: [
      { name: "Gạo tẻ & gạo nếp xay mịn", amount: "150g", estimatedPrice: 5000 },
      { name: "Sườn non sụn giòn", amount: "250g", estimatedPrice: 22000 },
      { name: "Quẩy giòn", amount: "2 đôi", estimatedPrice: 4000 },
      { name: "Hành lá, tía tô, tiêu đen", amount: "ít", estimatedPrice: 2000 },
      { name: "Ruốc thịt (chà bông)", amount: "20g", estimatedPrice: 4000 },
    ],
    steps: [
      "Ninh sườn sụn mềm lấy nước ngọt trong 30 phút",
      "Hòa bột gạo vào nước ninh sườn khuấy đều tay lửa nhỏ đến khi sánh mịn",
      "Nêm gia vị vừa miệng, cháo trắng mịn như lụa",
      "Múc cháo nóng ra bát, gắp sườn sụn giòn sần sật",
      "Cắt quẩy giòn, rắc ruốc thịt và thật nhiều tiêu ớt thơm lừng",
    ],
    rating: 4.7,
    reviews: 165,
  },
  {
    id: "recipe-013",
    name: "Đậu hũ sốt cà chua hành hoa",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800",
    calories: 260,
    cookTime: 15,
    servings: 2,
    cost: 16000,
    category: "chay",
    tags: ["siêu tiết kiệm", "thanh tịnh", "dễ nấu"],
    ingredients: [
      { name: "Đậu hũ trắng mơ", amount: "3 bìa", estimatedPrice: 9000 },
      { name: "Cà chua chín mọng", amount: "2 quả", estimatedPrice: 4000 },
      { name: "Hành hoa & mùi tàu", amount: "1 nhúm", estimatedPrice: 2000 },
      { name: "Dầu hào chay, nước mắm", amount: "vừa đủ", estimatedPrice: 2000 },
    ],
    steps: [
      "Cắt đậu hũ miếng vuông, chiên vàng giòn các mặt",
      "Phi thơm đầu hành lá, xào cà chua nát thành sốt sệt",
      "Nêm chút đường, dầu hào, hạt nêm cho đậm vị sốt",
      "Thả đậu hũ chiên vào rim lửa nhỏ 5 phút ngấm sốt đỏ",
      "Rắc hành hoa thái nhỏ, ăn kèm cơm trắng cực trôi cơm",
    ],
    rating: 4.6,
    reviews: 74,
  },
  {
    id: "recipe-014",
    name: "Chè hạt sen long nhãn",
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800",
    calories: 210,
    cookTime: 30,
    servings: 3,
    cost: 25000,
    category: "an-vat",
    tags: ["ngọt thanh", "an thần", "tráng miệng"],
    ingredients: [
      { name: "Hạt sen tươi Huế", amount: "150g", estimatedPrice: 18000 },
      { name: "Long nhãn Hưng Yên", amount: "80g", estimatedPrice: 15000 },
      { name: "Đường phèn thanh mát", amount: "100g", estimatedPrice: 4000 },
      { name: "Lá dứa thơm", amount: "2 lá", estimatedPrice: 1000 },
    ],
    steps: [
      "Hầm hạt sen với nước lá dứa đến khi chín bở tơi mà không nát",
      "Khéo léo lồng từng hạt sen vào trong cùi long nhãn",
      "Nấu nước đường phèn thanh trong, thả long nhãn bọc sen vào",
      "Đun sôi nhẹ 2 phút rồi tắt bếp để giữ độ giòn của nhãn",
      "Ăn nóng hoặc thêm đá lạnh giải nhiệt sảng khoái",
    ],
    rating: 4.9,
    reviews: 98,
  },
  {
    id: "recipe-015",
    name: "Trái cây dầm sữa chua hạt chia",
    image: "/images/img-foodsaver/Gi%E1%BB%8F%20tr%C3%A1i%20c%C3%A2y%20rau%20c%E1%BB%A7%20t%C6%B0%C6%A1i%20r%E1%BB%B1c%20r%E1%BB%A1.png",
    calories: 180,
    cookTime: 5,
    servings: 1,
    cost: 18000,
    category: "an-vat",
    tags: ["healthy", "vitamin C", "đẹp da"],
    ingredients: [
      { name: "Sữa chua không đường", amount: "1 hộp", estimatedPrice: 7000 },
      { name: "Xoài, thanh long, dưa hấu", amount: "150g", estimatedPrice: 10000 },
      { name: "Hạt chia hữu cơ", amount: "1 muỗng", estimatedPrice: 3000 },
      { name: "Sữa đặc hoặc mật ong", amount: "1 thìa nhỏ", estimatedPrice: 1000 },
    ],
    steps: [
      "Cắt các loại trái cây tươi thành miếng vuông vừa ăn",
      "Cho đá bào hoặc đá viên vào ly",
      "Xếp các lớp trái cây rực rỡ sắc màu lên trên đá",
      "Đổ hộp sữa chua mát lạnh, rưới chút mật ong và rắc hạt chia",
      "Trộn đều và thưởng thức ngay món ăn xế thanh mát lành mạnh",
    ],
    rating: 4.8,
    reviews: 153,
  },
  {
    id: "recipe-016",
    name: "Bún chả giò rau sống",
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=800",
    calories: 460,
    cookTime: 25,
    servings: 2,
    cost: 26000,
    category: "bun-pho",
    tags: ["giòn rụm", "dễ ăn", "bữa trưa"],
    ingredients: [
      { name: "Chả giò tôm thịt chiên giòn", amount: "6 cuốn", estimatedPrice: 24000 },
      { name: "Bún tươi sợi nhỏ", amount: "300g", estimatedPrice: 6000 },
      { name: "Rau sống & dưa leo bào", amount: "1 đĩa", estimatedPrice: 5000 },
      { name: "Đậu phộng rang & mỡ hành", amount: "1 chén", estimatedPrice: 3000 },
      { name: "Nước mắm chua ngọt pha tỏi ớt", amount: "1 chén", estimatedPrice: 3000 },
    ],
    steps: [
      "Chiên chả giò ngập dầu đến khi vàng ruộm giòn tan",
      "Xếp bún tươi vào tô, thêm dưa leo băm, rau thơm thái nhỏ",
      "Cắt chả giò thành từng miếng vừa ăn xếp lên mặt bún",
      "Rưới mỡ hành bóng bẩy và rắc đầm đậu phộng rang giã dập",
      "Chan nước mắm chua ngọt tỏi ớt, trộn đều và thưởng thức vị giòn đậm",
    ],
    rating: 4.8,
    reviews: 119,
  },
];

export const PARTNER_LISTINGS_DATA = [
  {
    id: "list-seed-0001",
    partnerId: "part-prof-0001",
    title: "Túi Thần Kỳ Bánh Mì Pháp & Croissant Dư Trong Ngày",
    description: "Gồm bánh mì baguette nướng giòn hôm nay và croissant bơ Pháp béo ngậy.",
    category: "BAKERY",
    originalPrice: 120000,
    discountPrice: 39000,
    quantity: 6,
    unit: "túi",
    imageUrls: ["https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600"],
    status: "AVAILABLE",
  },
  {
    id: "list-seed-0002",
    partnerId: "part-prof-0001",
    title: "Combo 4 Bánh Mì Ốp La Giờ Vàng",
    description: "Bánh mì giòn nóng kèm trứng và pate chuẩn bị cho buổi sáng tiết kiệm.",
    category: "BAKERY",
    originalPrice: 80000,
    discountPrice: 29000,
    quantity: 8,
    unit: "combo",
    imageUrls: ["https://images.unsplash.com/photo-1509722747041-616f39b57569?w=800"],
    status: "AVAILABLE",
  },
  {
    id: "list-seed-0003",
    partnerId: "part-prof-0003",
    title: "Cơm Tấm Sườn Nướng Giờ Vàng (Dư Trưa)",
    description: "Cơm tấm nóng thơm sườn nướng mắm ớt than hoa, kèm bì chả trứng hấp.",
    category: "COOKED_MEAL",
    originalPrice: 75000,
    discountPrice: 28000,
    quantity: 10,
    unit: "phần",
    imageUrls: ["/images/img-foodsaver/C%C6%A1m%20s%C6%B0%E1%BB%9Dn%20n%C6%B0%E1%BB%9Bng%20tr%E1%BB%A9ng%20%E1%BB%91p%20la.png"],
    status: "AVAILABLE",
  },
  {
    id: "list-seed-0004",
    partnerId: "part-prof-0003",
    title: "Set Canh Chua Cá Lóc & Cơm Trưa Gia Đình",
    description: "Canh chua cá lóc rau bắp chuối dứa me chua ngọt thanh mát chuẩn vị.",
    category: "COOKED_MEAL",
    originalPrice: 85000,
    discountPrice: 32000,
    quantity: 5,
    unit: "set",
    imageUrls: ["https://images.unsplash.com/photo-1547592180-85f173990554?w=800"],
    status: "AVAILABLE",
  },
  {
    id: "list-seed-0005",
    partnerId: "part-prof-0001",
    title: "Tô Bún Bò Huế Cốt Đậm Đà Bán Trưa Dư",
    description: "Bún bò Huế bắp giò hầm mắm ruốc thơm lừng kèm rau sống và ớt chưng.",
    category: "COOKED_MEAL",
    originalPrice: 70000,
    discountPrice: 30000,
    quantity: 7,
    unit: "tô",
    imageUrls: ["https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800"],
    status: "AVAILABLE",
  },
  {
    id: "list-seed-0006",
    partnerId: "part-prof-0003",
    title: "Phở Bò Hà Nội Nước Dùng Hầm Xương Thảo Quả",
    description: "Phở bò thơm phức quế hồi thảo quả nạm bò mềm ngậy nóng hổi.",
    category: "COOKED_MEAL",
    originalPrice: 75000,
    discountPrice: 29000,
    quantity: 5,
    unit: "tô",
    imageUrls: ["https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800"],
    status: "AVAILABLE",
  },
  {
    id: "list-seed-0007",
    partnerId: "part-prof-0002",
    title: "Khay Gỏi Cuốn Tôm Thịt Nước Tương Đậu Phộng",
    description: "Gỏi cuốn tôm sú thịt ba chỉ tươi trong ngày chấm xốt tương béo thơm.",
    category: "GROCERIES",
    originalPrice: 60000,
    discountPrice: 25000,
    quantity: 12,
    unit: "khay",
    imageUrls: ["https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800"],
    status: "AVAILABLE",
  },
  {
    id: "list-seed-0008",
    partnerId: "part-prof-0002",
    title: "Hộp Xôi Xéo Mỡ Hành Ruốc Nóng Hổi",
    description: "Xôi nếp dẻo thơm hạt sen đỗ xanh mỡ hành béo ngậy ruốc thịt.",
    category: "BAKERY",
    originalPrice: 35000,
    discountPrice: 15000,
    quantity: 8,
    unit: "hộp",
    imageUrls: ["https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800"],
    status: "AVAILABLE",
  },
  {
    id: "list-seed-0009",
    partnerId: "part-prof-0002",
    title: "Túi Trái Cây Tươi Theo Mùa Cắt Sẵn",
    description: "Dưa hấu, xoài cát, thanh long ruột đỏ tươi ngon cắt sẵn trong ngày.",
    category: "GROCERIES",
    originalPrice: 45000,
    discountPrice: 19000,
    quantity: 15,
    unit: "túi",
    imageUrls: ["/images/img-foodsaver/Gi%E1%BB%8F%20tr%C3%A1i%20c%C3%A2y%20rau%20c%E1%BB%A7%20t%C6%B0%C6%A1i%20r%E1%BB%B1c%20r%E1%BB%A1.png"],
    status: "AVAILABLE",
  },
  {
    id: "list-seed-0010",
    partnerId: "part-prof-0003",
    title: "Cơm Rang Dưa Bò Giòn Cháy Cạnh",
    description: "Cơm rang tơi hạt xào thịt bò thăn mềm và dưa cải chua giòn đậm đà.",
    category: "COOKED_MEAL",
    originalPrice: 65000,
    discountPrice: 27000,
    quantity: 9,
    unit: "phần",
    imageUrls: ["https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800"],
    status: "AVAILABLE",
  },
];

export const SAMPLE_MEAL_PLANS = [
  // 2026-10-04 (Full 4 meals)
  {
    date: "2026-10-04",
    slot: "breakfast",
    meal: "Bánh mì ốp la pate",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?w=800",
    calories: 380,
    cost: 15000,
    ingredients: ["Bánh mì", "Trứng", "Pate"],
  },
  {
    date: "2026-10-04",
    slot: "lunch",
    meal: "Cơm tấm sườn bì chả",
    image: "/images/img-foodsaver/C%C6%A1m%20s%C6%B0%E1%BB%9Dn%20n%C6%B0%E1%BB%9Bng%20tr%E1%BB%A9ng%20%E1%BB%91p%20la.png",
    calories: 650,
    cost: 35000,
    ingredients: ["Gạo tấm", "Sườn heo", "Bì heo", "Trứng"],
  },
  {
    date: "2026-10-04",
    slot: "dinner",
    meal: "Canh chua cá lóc",
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=800",
    calories: 280,
    cost: 32000,
    ingredients: ["Cá lóc", "Dứa", "Cà chua", "Bạc hà"],
  },
  {
    date: "2026-10-04",
    slot: "snack",
    meal: "Trái cây dầm sữa chua",
    image: "/images/img-foodsaver/Gi%E1%BB%8F%20tr%C3%A1i%20c%C3%A2y%20rau%20c%E1%BB%A7%20t%C6%B0%C6%A1i%20r%E1%BB%B1c%20r%E1%BB%A1.png",
    calories: 180,
    cost: 18000,
    ingredients: ["Sữa chua", "Xoài", "Thanh long"],
  },

  // 2026-10-05 (Full 4 meals)
  {
    date: "2026-10-05",
    slot: "breakfast",
    meal: "Xôi xéo mỡ hành ruốc",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800",
    calories: 420,
    cost: 18000,
    ingredients: ["Gạo nếp", "Đậu xanh", "Hành phi"],
  },
  {
    date: "2026-10-05",
    slot: "lunch",
    meal: "Cơm rang dưa bò",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800",
    calories: 480,
    cost: 25000,
    ingredients: ["Cơm nguội", "Thịt bò", "Dưa chua"],
  },
  {
    date: "2026-10-05",
    slot: "dinner",
    meal: "Thịt kho tàu trứng cút",
    image: "/images/img-foodsaver/B%E1%BB%AFa%20c%C6%A1m%20Vi%E1%BB%87t%20n%C3%B3ng%20h%E1%BB%95i%20d%C3%A2n%20d%C3%A3.png",
    calories: 550,
    cost: 32000,
    ingredients: ["Thịt ba chỉ", "Trứng cút", "Nước dừa"],
  },
  {
    date: "2026-10-05",
    slot: "snack",
    meal: "Chè hạt sen long nhãn",
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800",
    calories: 210,
    cost: 25000,
    ingredients: ["Hạt sen", "Long nhãn", "Đường phèn"],
  },

  // 2026-10-06 (3 meals: breakfast, lunch, dinner)
  {
    date: "2026-10-06",
    slot: "breakfast",
    meal: "Phở bò tái nạm",
    image: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800",
    calories: 450,
    cost: 28000,
    ingredients: ["Bánh phở", "Bắp bò", "Nạm bò"],
  },
  {
    date: "2026-10-06",
    slot: "lunch",
    meal: "Bún bò Huế",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800",
    calories: 520,
    cost: 30000,
    ingredients: ["Bún tươi", "Bắp bò", "Mắm ruốc"],
  },
  {
    date: "2026-10-06",
    slot: "dinner",
    meal: "Gỏi cuốn tôm thịt",
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800",
    calories: 220,
    cost: 22000,
    ingredients: ["Bánh tráng", "Tôm", "Thịt ba chỉ", "Bún"],
  },

  // 2026-10-07 (2 meals: lunch & dinner)
  {
    date: "2026-10-07",
    slot: "lunch",
    meal: "Salad ức gà sốt mè rang",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800",
    calories: 320,
    cost: 24000,
    ingredients: ["Ức gà", "Xà lách", "Cà chua bi", "Sốt mè"],
  },
  {
    date: "2026-10-07",
    slot: "dinner",
    meal: "Đậu hũ sốt cà chua hành hoa",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800",
    calories: 260,
    cost: 16000,
    ingredients: ["Đậu hũ", "Cà chua", "Hành hoa"],
  },

  // 2026-10-08 (1 meal: breakfast)
  {
    date: "2026-10-08",
    slot: "breakfast",
    meal: "Cháo sườn sụn quẩy giòn",
    image: "https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=800",
    calories: 390,
    cost: 20000,
    ingredients: ["Gạo tẻ", "Sườn sụn", "Quẩy giòn"],
  },
];

async function seedMealPlanner() {
  console.log('[MealPlanner] Ensuring Partner Profiles and Listings...');
  // Ensure verified status for partner 1, 2, 3
  await prisma.partnerProfile.updateMany({
    where: { id: { in: ['part-prof-0001', 'part-prof-0002', 'part-prof-0003'] } },
    data: { verificationStatus: 'VERIFIED' },
  });

  for (const item of PARTNER_LISTINGS_DATA) {
    await prisma.listing.upsert({
      where: { id: item.id },
      update: {
        title: item.title,
        description: item.description,
        discountPrice: item.discountPrice,
        originalPrice: item.originalPrice,
        quantity: item.quantity,
        unit: item.unit,
        imageUrls: item.imageUrls,
        status: item.status,
      },
      create: {
        id: item.id,
        partnerId: item.partnerId,
        title: item.title,
        description: item.description,
        category: item.category,
        originalPrice: item.originalPrice,
        discountPrice: item.discountPrice,
        quantity: item.quantity,
        unit: item.unit,
        expiryAt: new Date(Date.now() + 24 * 3600 * 1000),
        pickupStartTime: new Date(),
        pickupEndTime: new Date(Date.now() + 8 * 3600 * 1000),
        pickupAddress: 'Địa chỉ đối tác FoodSaver TP.HCM',
        lat: 10.7712,
        lng: 106.6908,
        geohash: 'w4rwt2',
        imageUrls: item.imageUrls,
        safetyNotes: 'Bảo quản mát, dùng ngon nhất trong ngày',
        status: item.status,
        urgencyScore: 0.8,
        wasteRisk: 'HIGH',
      },
    });
  }

  console.log('[MealPlanner] Seeding 16 comprehensive recipes with photos...');
  for (const r of RECIPES_DATA) {
    await prisma.recipe.upsert({
      where: { id: r.id },
      update: r,
      create: r,
    });
  }

  console.log('[MealPlanner] Seeding October 2026 Meal Plans with photos...');
  for (const m of SAMPLE_MEAL_PLANS) {
    const existing = await prisma.mealPlan.findFirst({
      where: { date: m.date, slot: m.slot, userId: null },
    });
    if (existing) {
      await prisma.mealPlan.update({
        where: { id: existing.id },
        data: m,
      });
    } else {
      await prisma.mealPlan.create({
        data: {
          ...m,
          userId: null,
        },
      });
    }
  }

  console.log('[MealPlanner] Seeding completed successfully!');
}

seedMealPlanner()
  .catch((e) => {
    console.error('[MealPlanner] Seeding error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
